# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ba07ecdaa03401a613b38e7ed57d3640717bec49b966a693d3cccaa3529f7269b922c26ae705c157baee2a72f9beef837faa80e88776c41720a21643dd43b5

test:
  secret_key_base: c812862ce3d2f205d21d925f17d8e9f5f8afb14db7461a020217de56895cd649fcfea8ce10b9b6e60080bcc24fd2938e6b169acaa29d0b6ed2d0a8807522ce08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
